name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    if: ${{ !startsWith(github.event.head_commit.message, 'release:') }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [22.x]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2

      - name: Install
        run: bun install

      - name: Test
        run: |
          bun run build
          bun run test
          bun run typecheck
